version: '3'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: build-container
    volumes:
      - data:/rtype

  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-container
    volumes:
      - data:/rtype
    depends_on:
      - builder
volumes:
  data: