version: '3'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: build-container
    volumes:
      - data:/rtype
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: run-container
    volumes:
      - data:/rtype
    ports:
      - "4244:4244"
      - "4210-4220:4210-4220/udp"
    depends_on:
      - builder
volumes:
  data: