name: Clang-Format

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your main branch

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: |
        sudo apt-get update -q
        sudo apt-get install clang-format

    - name: Run clang-format
      run: |
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style=file -i {} \;

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-format code"
        git push
