name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: adamelm/r-type-compiler:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build .
    - name: Build package
      run: cd build && cpack