name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        conan_os: [Linux, MacOS, Windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install CMake
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get install -y cmake
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        fi
    - name: Set up Conan
      run: |
        pip install conan
        conan profile detect --force

    - name: Test compilation with conan & cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        conan install ..
        cmake --build .
        cmake --build . --target run
